substitutions:
  devicename: heatpump

esphome:
  name: esp8266-test
  friendly_name: ESP8266-Test

esp8266:
  board: esp12e

logger:
  level: DEBUG
  baud_rate: 115200

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "ESP8266-Test-Fallback"
    password: "testpassword123"

captive_portal:

sensor:
  - platform: uptime
    name: "Uptime"
    
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: status
    name: "Status"
